import type { MessageContent } from "../types/content";

// Source of truth for every displayed line. Keep content separate from scene
// presentation so pacing can evolve without scattering copy through components.
export const message: MessageContent = {
  herName: "you",
  yourName: "me",
  opening: {
    initialLines: [
      { text: "There's something I've been meaning to tell you." },
      { text: "So… I made this." },
      { text: "I wasn't really sure how to say it." },
      { text: "So I thought I'd write it instead." },
    ],
    ctaText: "OPEN THIS →",
    revealLine: "I hope you'll hear me out.",
  },
  scenes: {
    "ordinary-class": {
      lines: [
        { text: "It started in a pretty ordinary class." },
        { text: "Honestly, the class was boring." },
        { text: "But I still showed up." },
        { text: "And then, one day…" },
        { text: "I noticed you." },
      ],
    },
    "noticed-you": {
      lines: [
        { text: "I was sitting pretty far away." },
        { text: "You were just sitting there, scrolling on your phone, casually pulling your hair behind your ear." },
        { text: "And for some reason…" },
        { text: "I noticed you." },
      ],
    },
    beautiful: {
      lines: [
        { text: "My first thought was simple." },
        { text: "“She’s beautiful.”", emphasis: true },
        { text: "I don't really know what I felt at that moment." },
        { text: "Maybe curiosity." },
        { text: "Maybe something else." },
        { text: "I honestly couldn't name it." },
      ],
    },
    growing: {
      lines: [
        { text: "That little moment didn't really disappear." },
        { text: "It kept growing.", emphasis: true },
        { text: "I started catching myself looking at you during class." },
        { text: "Sometimes instead of paying attention to the lecture…" },
        { text: "I was paying attention to you. 😂" },
        { text: "And, obviously, I tried not to get caught." },
        { text: "I wasn't thinking about anything complicated." },
        { text: "I just liked looking at you." },
      ],
    },
    "little-reasons": {
      lines: [
        { text: "Eventually, I started wanting to talk to you." },
        { text: "The problem was…" },
        { text: "I had absolutely no idea how." },
        { text: "I didn't know what to say." },
        { text: "I didn't know how to start a conversation without making it weird." },
        { text: "So I started finding little reasons." },
      ],
    },
    interactions: {
      lines: [
        { text: "When we got to choose our project groups, I chose yours." },
        { text: "Not because I had some master plan. 😂" },
        { text: "I just wanted a little more time around you." },
        { text: "And then there were all these tiny interactions." },
        { text: "Like the time I asked you for help with printing.", emphasis: true },
        { text: "I could have gone to a stationery shop myself." },
        { text: "But I asked you anyway." },
        { text: "Because it gave me a reason to talk to you a little longer." },
        { text: "And honestly…" },
        { text: "those small conversations made me weirdly happy.", emphasis: true },
      ],
    },
    "little-things": {
      lines: [
        { text: "I liked hearing you talk. 🎵🎶" },
        { text: "I liked your voice. ❄️" },
        { text: "I liked being around you. 🤍" },
        { text: "Nothing huge happened." },
        { text: "But somehow, those little moments started meaning something to me." },
        { text: "Maybe that's why I kept finding little excuses to spend a bit more time with you." },
      ],
    },
    "kind-of": {
      lines: [
        { text: "And then there was this one small moment." },
        { text: "You asked me:" },
        { text: "“Are you going home?”", emphasis: true },
        { text: "And I answered:" },
        { text: "“Kind of.” 😂", emphasis: true },
        { text: "Yeah." },
        { text: "That's it. 😂" },
        { text: "Almost immediately afterward, I thought:" },
        { text: "“Why the hell did I say that?”", emphasis: true },
        { text: "I could've just said:" },
        { text: "“I'm getting bored, so I'm probably going to the café. Do you want to come?”", emphasis: true },
        { text: "Maybe you would've said yes." },
        { text: "Maybe you would've said no." },
        { text: "I honestly don't know." },
        { text: "I just wish I'd been a little more confident." },
      ],
    },
    "honest-part": {
      lines: [
        { text: "Somewhere along the way…" },
        { text: "I realized I genuinely like you.", emphasis: true },
        { text: "I don't have some perfect explanation for why." },
        { text: "I like your smile. 🌸" },
        { text: "I like your eyes. 🏵️" },
        { text: "I like your voice. 🍁" },
        { text: "I like the way you talk. 🌿" },
        { text: "But even those aren't really the answer." },
        { text: "I just do.", emphasis: true },
        { text: "I've had this sitting in my head for a while." },
        { text: "So I decided I'd rather tell you than wonder later…" },
        { text: "“Why didn't I just tell her?”", emphasis: true },
        { text: "So I'm telling you now." },
      ],
    },
  },
  noExpectations: {
    lines: [
      { text: "I want to make one thing clear." },
      { text: "I'm not expecting anything from you." },
      { text: "I didn't make this so you'd feel like you have to give me an answer." },
      { text: "I just wanted you to know how I feel." },
      { text: "Whatever you feel about it…" },
      { text: "I respect that." },
      { text: "We don't really know each other that well yet." },
      { text: "So maybe we could just start there." },
      { text: "Talk a little more." },
      { text: "Get to know each other." },
      { text: "And, if you're comfortable with it…" },
      { text: "maybe we could grab a coffee after finals and see where it goes. ☕" },
    ],
    choices: {
      coffeeLabel: "☕ Let's get that coffee",
      appreciationLabel: "🤍 I appreciate you telling me",
    },
  },
  finalMessage: {
    coffee: {
      lines: [
        { text: "Well… looks like we're getting that coffee. ☕" },
        { text: "I don't know what this could become." },
        { text: "And honestly, I don't think we need to know yet." },
        { text: "We barely know each other." },
        { text: "So maybe we start there." },
        { text: "One coffee." },
        { text: "A proper conversation." },
        { text: "No expectations." },
        { text: "Just a chance to get to know each other." },
        { text: "And this time…" },
        { text: "I promise I'll have a better answer than:" },
        { text: "“Kind of.” 😂", emphasis: true },
        { text: "You know where to find me." },
        { text: "Just text me." },
      ],
    },
    appreciation: {
      lines: [
        { text: "Thanks for hearing me." },
        { text: "I really mean that." },
        { text: "I wasn't expecting you to feel the same way." },
        { text: "I just wanted to be honest with you." },
        { text: "Whatever you feel about it…" },
        { text: "I respect that." },
        { text: "There's nothing you need to explain." },
        { text: "Nothing you need to force." },
        { text: "I'm just glad I finally said what had been sitting in my head for so long." },
        { text: "Take care. 🤍" },
        { text: "And…" },
        { text: "please don't block me. 😂" },
      ],
      secondaryPrompt: "Did you actually mean that, or did your finger betray you? 😂",
      secondaryReveal: [
        { text: "😂 Okay, okay." },
        { text: "I'll pretend that didn't happen." },
        { text: "You can go back to the original two options if you want to see what the other one says." },
        { text: "(You can check it just out of curiosity — no pressure. 😂)" },
      ],
      backButtonLabel: "← Back to the two options",
    },
  },
};
